### ISSUE TITLE
Status messages are being cut off by filter bar on index page

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-compass#100]
### Describe the Bug
At the moment the status messages on the index page are partly covered by the filter bar. Since we need status messages on the index page, we need to come up with a solution where the status messages are in their entirety readable.

### Steps to Reproduce

1. On index page click on an offer. In the detail overlay click on "Report"
2. On the report page fill out the form
3. You're being redirected to the index page with a status message on top of the page. However the status message is not entirely readable.

### Expected Behavior

A readable status message

### Actual Behavior

Part of the status message is overlapped by the filter bar on the index page

### Additional Information

This issue appears only after #98 is merged.

![Screenshot from 2023-08-16 13-11-45](https://github.com/digitalfabrik/integreat-compass/assets/72705147/431ae585-e144-4431-8b0d-c8c26a71f179)

<details>
  <summary>Traceback</summary>

  ```
  ```
</details>

**Comment by IsabellaTG** [comment]
Suggestion: 
1) Use toast message and show on first level (over navigation bar and overlay) (e.g. https://tailwindui.com/components/application-ui/feedback/alerts) 
2) Show notification on the right corner (e.g. https://tailwindui.com/components/application-ui/overlays/notifications)
