### ISSUE TITLE
"Edit Offer" form can be accessed even for offers the user didn't create

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-compass#103]
### Describe the Bug

We have a security hole. As logged in offer provider you still can access offers you didn't create via the URL manipulation.

### Steps to Reproduce

1. Log in as offer provider
2. Go to "my offers" and click on "Edit offer"
3. In edit offer form change the offer id to an offer id that you didn't create
4. See the form of the offer you didn't create

### Expected Behavior

User can only see the offers they created and if they try to edit offers they didn't create get a PermissionDenied error

### Actual Behavior

User can switch via the URL also to offers they didn't create

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```
</details>

**Comment by charludo** [comment]
Thank you for noticing this!!
