### ISSUE TITLE
Include missing offer details in the offer details overlay

### ISSUE THREAD

**Issue by charludo** [digitalfabrik/integreat-compass#107]
### Motivation

All relevant offer details should be shown (that's why we are asking for them after all! 😄)

### User Story

As a user, I want to get as much information as possible on each offer.

### Proposed Solution

Add the following bits of information which we are already collecting, but not showing to users:
- offer language
- is the offer free?
- group type
- mode type
- organization website
- (optional) a map with a pin at the address; this would be nice-to-have (since seeing a location on a map is much more intuitive than reading an unknown address, then having to search for the address on maps yourself), however we could also move this to the backlog

### Additional Context

Not sure if we need UI/UX for this - it's mostly just additional details lines in the left column.

**Comment by JoeyStk** [comment]
Also resolved by #108
