### ISSUE TITLE
Add price filter 

### ISSUE THREAD

**Issue by charludo** [digitalfabrik/integreat-compass#120]
### Motivation

Part of the MVP

### User Story

As a user, I want to be able to filter for free offers.

### Proposed Solution

Add the filter.

### Alternatives

-

### Additional Context

-

### Screenshots

-

**Comment by JoeyStk** [comment]
So far we only have the data in [our model](https://github.com/digitalfabrik/integreat-compass/blob/develop/integreat_compass/cms/models/offers/offer_version.py) whether or not an offer is free or not. With that in mind I would argue that a checkbox "Only show free offers" should be sufficient as a filter. Do you agree or would you prefer a range slider with which I can filter offers like "Show all offers that cost less than 50€"?

**Comment by charludo** [comment]
> So far we only have the data in [our model](https://github.com/digitalfabrik/integreat-compass/blob/develop/integreat_compass/cms/models/offers/offer_version.py) whether or not an offer is free or not. With that in mind I would argue that a checkbox "Only show free offers" should be sufficient as a filter. Do you agree or would you prefer a range slider with which I can filter offers like "Show all offers that cost less than 50€"?

Agreed, checkbox should be fine!
