### ISSUE TITLE
Button "Add offer" on mouseover barely legible

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-compass#125]
### Describe the Bug

The "Add offer" button in the "My Offers" view is barely readable.

### Steps to Reproduce

1. Login as offer provider
2. Go to "My Offers"
3. Mouseover effect on "Add offer" button
4. See that the text is in yellow and therefore barely legible

### Expected Behavior

Also on mouseover effect the text should be legible

### Actual Behavior

Text on mouseover effect is barely legible

### Additional Information

Use text-gray-700 instead of text-primary as the hover effect for this button

<details>
  <summary>Traceback</summary>

  ```
  ```
</details>

**Comment by JoeyStk** [comment]
Maybe this is a good issue for @amikable-tech?

**Comment by paoloevan** [comment]
hello, I am a beginners and I like your project. I could try to contribute in this!

**Comment by JoeyStk** [comment]
Hello @paoloevan, thank you for your interest in our project. Please feel free to tackle this issue if you like :)
