### ISSUE TITLE
filter chips have a shadow

### ISSUE THREAD

**Issue by IsabellaTG** [digitalfabrik/integreat-compass#135]
### Steps to Reproduce

1. Go to 'https://compass-test.tuerantuer.org/?'
2. See Filter area on the left side

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```
</details>

**Comment by JoeyStk** [comment]
I think what needs to be done here is to only display the class shadow-lg on mouseover on the filter chips
