### ISSUE TITLE
Feedback after address input is missing 

### ISSUE THREAD

**Issue by IsabellaTG** [digitalfabrik/integreat-compass#136]
### Steps to Reproduce

1. Go to 'https://compass-test.tuerantuer.org/?lat=48.3780446&long=10.8879783'
2. See filter area on the right side
3. Scroll down to 'Location.'
4. Type in "Wertachstraße 29, 86153 Augsburg"
5. Loading indicator is shown
6. Type in "Augsburgerstraße 120, Ingolstadt"
7. Not clear if input was successful -> not even loading indicator is shown like after step 4) 

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```
</details>

**Comment by charludo** [comment]
@IsabellaTG "Augsburgerstraße 120, Ingolstadt" does not appear to be an actual address, so the map can't really react to it. 
#132 adjusted the default zoom level, so the user should be able to see this now. 

Therefore I'd suggest closing this issue if that's OK with you.

**Comment by IsabellaTG** [comment]
oh ok, the wrong address is by accident. Than I would still expect any information. Would it be possible to show the user an error message that the address is not existing?

**Comment by charludo** [comment]
> oh ok, the wrong address is by accident. Than I would still expect any information. Would it be possible to show the user an error message that the address is not existing?

Should be doable, yes.
