### ISSUE TITLE
Setting perimeter of location leads to error page 500

### ISSUE THREAD

**Issue by IsabellaTG** [digitalfabrik/integreat-compass#137]
### Steps to Reproduce

2. got filter area on the right
3. Scroll down to 'location'
4. Enter "Wertachstraße 29, 86153 Augsburg"
5. Select any perimeter 

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```
</details>

**Comment by charludo** [comment]
@svenseeberg do your new logs spit out anything for this? I'm unable to reproduce the issue locally, but very easily can on the test server

**Comment by svenseeberg** [comment]
I think this is it:
```
Sep 13 15:30:33 ERROR   django.request - 500 Internal Server Error: /?lat=48.3780446&long=10.8879783&radius=5
Traceback (most recent call last):
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/integreat_compass/cms/views/index.py", line 94, in get
    filtered_offers = [
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/integreat_compass/cms/views/index.py", line 98, in <listcomp>
    float(offer.location.lat),
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by charludo** [comment]
> I think this is it:
> 
> ```
> Sep 13 15:30:33 ERROR   django.request - 500 Internal Server Error: /?lat=48.3780446&long=10.8879783&radius=5
> Traceback (most recent call last):
>   File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
>     response = get_response(request)
>   File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/integreat_compass/cms/views/index.py", line 94, in get
>     filtered_offers = [
>   File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/integreat_compass/cms/views/index.py", line 98, in <listcomp>
>     float(offer.location.lat),
> TypeError: float() argument must be a string or a number, not 'NoneType'
> ```

Thanks, this is very helpful indeed!
