### ISSUE TITLE
Duplicate icon in vote form (in German translation)

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-compass#149]
### Describe the Bug
When board members reject or accept offers the icon appears double. 

### Steps to Reproduce
0. If necessary language setting in browser settings to German 
1. Login as board member
2. Go to 'Applications'
3. Click on 'Reject offer'
4. See icon twice

### Expected Behavior

The icon should appear only once

### Actual Behavior

The icon appears twice

### Additional Information

This happens because in the German translation file there is a second icon appended additional to the one in the vote form.

Important file: [translation file](https://github.com/digitalfabrik/integreat-compass/blob/develop/integreat_compass/locale/de/LC_MESSAGES/django.po#L674) 

![image](https://github.com/digitalfabrik/integreat-compass/assets/72705147/1c151760-4f78-4214-b3f8-ce3a1fceb195)

**Comment by charludo** [comment]
I can't reproduce this, neither locally nor on the test server
