### ISSUE TITLE
Set up pyproject.toml

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-compass#2]
We need a basic pyproject.toml file that covers the basic install of the current Django modules. Further requirements are not yet defined.

**Comment by timoludwig** [comment]
Open questions:
- python project name (should be available on pypi)
- src folder layout or flat (Integreat & Lunes use flat)
- dependency Manager yes or no (e.g. Poetry), Integreat-cms is testing setup without (and only bash Script to bump the versions), until now it's working quite well, but has caveats (pinning dev versions is more complex, version conflicts are not automatically resolved)
- which minimum python version? (probably depends on packaged python version on desired production setup)
