### ISSUE TITLE
Offer Application

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-compass#37]
### Motivation
Offers are not immediately available to consumers (job center counselors). They first need to be admitted by a board (gate keeper). Organizations therefore need to apply with an offer.

### User Story
As a organization representative I want enter new offer ("Maßnahme") so that the offer can be found by job center employees and recommended to job center clients.

### Proposed Solution
- Add a form (login required) to enter details of an offer (title, description, contact, categories).
- The contact information has to be entered for each measure (offer) individually. The organisation information can be automatically completed from a list of existing organizations (no personal data).
- The success message should contain a message that the application "will be reviewed by the board of trustees".
- The location is excluded in this task (extra task #50 ).
- "Gesellschaftsform" should be replaced with "free of charge".

### Screenshots
![image](https://user-images.githubusercontent.com/15197000/233357387-88095d80-3bcc-42e5-8501-f59cf036ddf9.png)

**Comment by charludo** [comment]
> * Add a form (login required) to enter details of an offer (title, description, contact, categories).

Could we maybe integrate the registration form into the "Offer Application" form view? I.e. just above the "Submit offer" button, add some text "set a password to be able to edit this offer later" with mandatory email/password fields?

**Comment by svenseeberg** [comment]
@RhettCarpet there are a few open questions about the organisation information: Is the type of organisation really relevant? Wouldn't it be more useful to ask if the service provider is "non-profit" or "for profit"? Is it relevant if the costs can be covered by the Job Center or reimbursed?

**Comment by svenseeberg** [comment]
@charludo we changed one thing:

> "Gesellschaftsform" should be replaced with "free of charge".

**Comment by charludo** [comment]
> @charludo we changed one thing:
> 
> > "Gesellschaftsform" should be replaced with "free of charge".

Is this a yes/no field? Gesellschaftsform is not relevant any longer?

Also, does this mean we should remove the "Cost" field? Previously we decided that setting this to zero made an offer free of charge.

**Comment by svenseeberg** [comment]
> Is this a yes/no field? Gesellschaftsform is not relevant any longer?

Yes, it is yes/no. And yes, the Gesellschaftsform is obsolete.

> Also, does this mean we should remove the "Cost" field? Previously we decided that setting this to zero made an offer free of charge.

Yes. It seems that there are many cases where a single number is not really correct.
