### ISSUE TITLE
Vote on offer applications

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-compass#38]
### Motivation
Core functionality of the tool.

### User Story
As a board member I want to see pending offer applications so that I can vote to admit high quality applications.

### Proposed Solution
- Each user has exactly one vote.
- The vote can be changed until the offer has been finally rejected or accepted. The currently selected option can be highlighted by a check mark.
- An offer will be accepted/rejected when the quorum of voting users is reached.
- The threshold for accepting an offer should be 50% of users that are allowed to vote. As soon as 50,1% accept, the offer should be accepted.
- The threshold for accepted and declined offers should be configurable.

### Screenshots
![image](https://user-images.githubusercontent.com/15197000/233358236-026e4c28-fb8b-4bd0-a01b-b85785e1a54c.png)

**Comment by svenseeberg** [comment]
We need to clarify under which conditions an application will be marked as accepted. It is probably not a good idea to wait until all board members with permission to vote have voted. There are a few possible scenarios:
- After a fixed period the number of votes will be counted and any application that has more up- than down votes will be accepted. (what happens if there is an equal number of up and down votes?)
- The application is accepted as soon as a threshold of users have voted. There could be more board members than required votes.

On the long run we expect board members to not frequently look into new applications an cast their votes. That means we need to establish a mechanism that encourages new applications. This can be solved on an organisational level. But it would also be possible to send frequent e-mail reminders etc.

**Comment by ztefanie** [comment]
I think we got the information that:
1) A offer is accepted, when it has >= 5 accepts and zero declines
2) A offer is blocked when it has >= 1 declines

I think it should be possible to accept offers although one member has declined it. If a offer has 5 accepts it should be removed from the voting and is activated.

**Comment by svenseeberg** [comment]
> A offer is accepted, when it has >= 5 accepts and zero declines

Actually >=4. But we decided to make this dynamic, depending on the number of users that are allowed to vote. The threshold is 50%. As soon as more accept an offer, it is good to go.
