### ISSUE TITLE
View offer details

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-compass#40]
### Motivation
Core functionality of the tool.

### User Story
As a job center counselor I want to view the details of an offer so that I can provide necessary information (requirements, contact persons) about an offer to my client.

### Proposed Solution
- We do not have to implement all the details on the screenshot in the first phase. "IFK-Kommentare", "Erfolgsgeschichten" and "Bewertung" can be omitted. Also the menu link (3 vertical dots) is not required yet (we have no defined functionality for it).

### Alternatives
- None

### Additional Context
- None

### Screenshots
![image](https://user-images.githubusercontent.com/15197000/233360349-43e24c26-0aa0-4804-b6a8-34947e04f359.png)

**Comment by charludo** [comment]
> * We do not have to implement all the details on the screenshot in the first phase. "IFK-Kommentare", "Erfolgsgeschichten" and "Bewertung" can be omitted.

~~Ahh, this was were I'd seen mention of not implementing comments for now. @svenseeberg do you remember where you got that info from?~~

Ah I see, you just extracted this to #41. Makes sense, nevermind 😄 

> Also the menu link (3 vertical dots) is not required yet (we have no defined functionality for it).

In Figma this is where the "report" button goes, should we just put it directly onto the offer details card?
