### ISSUE TITLE
View my offers

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-compass#46]
### Motivation
We need a way for users to manage offers.

### User Story
As an organization representative I want to see all my offers and their status.

### Proposed Solution
- A simple list of all applications with status "pending", "accepted", "denied".
- Button to create new offer applications.
- Delete existing offers or applications.
- It should be possible to edit the location and contact info, type of offer. Categories, description, title, organisation name cannot be changed. If that needs to be changed, the user has to create a new application. We can add a sentence to the form that explains this process.

### Screenshots
![image](https://user-images.githubusercontent.com/15197000/234624345-ee0241d9-781a-4fb3-a51b-4abcd4a199ff.png)

**Comment by charludo** [comment]
> It should be possible to edit the location and contact info, type of offer. Categories, description, title, organisation name cannot be changed. If that needs to be changed, the user has to create a new application. We can add a sentence to the form that explains this process.

Is this still true?

AFAIK everythin should be change-able, but changing certain details results in a new version that has to be re-approved?

**Comment by charludo** [comment]
Does the user need to see how many votes they got and how many board members there are? I'd say no, is it alright if I leave this out? Seems to me the design has simply been copied & pasted from the voting view.
