### ISSUE TITLE
Add reporting functionality

### ISSUE THREAD

**Issue by charludo** [digitalfabrik/integreat-compass#88]
### Motivation

Users should be able to report offers.

### User Story

As a integration specialist or non-logged in user, I want to be able to report offers.

### Proposed Solution

Implement reporting functionality from the details overlay of offers. TBD: should a reason be providable / need to be provided?

### Screenshots

![image](https://github.com/digitalfabrik/integreat-compass/assets/47758554/3d7369f1-7c11-4a5f-9575-140c240169b7)

**Comment by JoeyStk** [comment]
@charludo / @svenseeberg My idea for this would be, that clicking on the "report" button leads to a new url (for example /offers/<id>/report/) with a short form to fill out the reason the reporting in a textarea. Do you think this sounds reasonable?

**Comment by charludo** [comment]
> @charludo / @svenseeberg My idea for this would be, that clicking on the "report" button leads to a new url (for example /offers/<id>/report/) with a short form to fill out the reason the reporting in a textarea. Do you think this sounds reasonable? 

I think it's either that or a modal, and a modal in a modal is not ideal I guess 😅
