### ISSUE TITLE
Add distance/location filter

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-compass#97]
### Motivation
Users should be able to filter offers by geographical location.

### User Story
As a job center councilor I want to filter offers by location so that the offers are physically reachable for my clients.

### Proposed Solution
- Add an input field that limits the distance of shown offers by distance to my location (default 25km).
- Add a Location setting to the offer filters (which is prefilled by the My Location setting from the profile)
- Use Nominatim API to resolve an entered address to coordinates
- Optional (prio low): Add a "My Location" setting in the profile
- Optional (prio low): use GPS to fill current location field

### Alternatives
- N/A

### Additional Context
- We could use [GeoPy](https://geopy.readthedocs.io/en/stable/)
- #39 

### Screenshots
![image](https://github.com/digitalfabrik/integreat-compass/assets/15197000/5f40405b-0695-488c-b742-43cfd42f8818)

**Comment by charludo** [comment]
> * Add a Location setting to the offer filters (which is prefilled by the My Location setting from the profile)

This is a new setting, right? Could an alternative be the location information provided by the browser? Because otherweise, we'll also need to add a ¨My profile"settings view
